### ISSUE TITLE
Were you able to get GraphQL-playground to work with Next?

### ISSUE THREAD

**Issue by junaid33** [kgoggin/next-graphql-playground#1]
I’m having the same issue and I don’t think playground is SSR compatible. The other solution is to use a server.js and serve the playground from the server directly. Any thoughts?

**Comment by kgoggin** [comment]
Hi! To be honest I don't even really remember much about this - I think it was from a couple of years ago. I haven't done much with Next since the project I was working on back then, and I know they've made a bunch of improvements in the last couple of years, so I wouldn't be surprised if there's a better way to handle this. 

If you're setting up a graphql serverless endpoint with apollo-server, I think it'll render a GraphQL Playground instance out of the box if you hit it from a web browser. You could also download the stand-alone [GraphQL Playground App](https://github.com/prisma/graphql-playground/releases) and just use that. 

Hope that helps!
